%% Module: User | Prefix: USR
%% Versions included: v1.0.0
erDiagram
    USR_USER {
        uuid id PK
        string email
        string password
        string first_name
        string last_name
        string role
        string status
        boolean force_password_change
        timestamp last_login_at
        bigint version
        timestamp created_at
        string created_by
        timestamp updated_at
        string updated_by
    }
